### PR TITLE
Limestone

### PR DESCRIPTION
**Pull request by Hanse00**
What do you think about merging this in now @yonsaber?

Or should I add world gen before we do it:question:

### CODE REVIEW

**Comment by yonsaber** [comment]
We should go for world gen before merging, just allows us to put the block into action.

**Comment by Hanse00** [comment]
Alright, world gen is in! :smile: 


It's set up with the following parameters:
- Try to make veins 32 in size
- Generate between level 32 and 128
- Try to generate 30 veins per chunk

What do you think? We can tweak those numbers as we see fit.

**Comment by Hanse00** [comment]
Should we maybe add a cobblestone version of limestone, and limestone blocks?
Just to add a bit to the possible aesthetic uses of it.

**Comment by Hanse00** [comment]
Okay @yonsaber, I think we're done with the limestone for now.

I've added a cobble and brick version of it, as you can see below.



Limestone drops cobble limestone, which can be smelted back into limestone, and then crafted 2x2 to get 4 limestone bricks. Basically the same functions as regular stone has.

**Comment by yonsaber** [comment]
ToDo: Configurable number of veins per chunk.

This is looking all good :) Nice work!

**Comment by Hanse00** [comment]
Added that as an issue, see #4 

Deleting branch.

**Pull request merged**
