### PR TITLE
Setup ForgeGradle workspace

### PR DESCRIPTION
**Pull request by Hanse00**
This should give us all the files needed to setup the workspace locally with just a simple forgegradle command, without containing all sorts of silly binaries and eclipse specific files.

How does it look to you @yonsaber?

Wanted to make sure we're both in on it before I start merging stuff into master, figure that's the best way to make sure we're both up to date on the project.

### CODE REVIEW

**Comment by yonsaber** [comment]
This all looks good and a good idea to get us both up to date before starting the bulk of the work.

As we spoke about we need to create an install guide so either of us can set up this project and be up to date with the code base.

We also need to look into an easy to use namespace that is reusable, something like `com.craftech` would be good for this mod but not reusable.

**Comment by Hanse00** [comment]
Got the guide for forgegradle up, does it seem clear enough?

**Comment by yonsaber** [comment]
Nice and clear, easy to understand.

**Comment by Hanse00** [comment]
Got the mod edited to fit our namespace, changed the mod ID and the mcmod.info file to fit our mod. Anything else we need to change before we pull this into the master branch?

**Comment by yonsaber** [comment]
Only the URL in the `mcmod.info` file needs to be modified to use the repo URL.
Also the `build.gradle` needs to be updated with the relevant information.

**Comment by Hanse00** [comment]
Alright, done.

Are we good to go?

**Comment by yonsaber** [comment]
We are good to go!

**Pull request merged**
