### PR TITLE
Textures

### PR DESCRIPTION
**Pull request by ajloveslily14**
Made blast furnace textures not look as bad as they did

### CODE REVIEW

**Comment by Hanse00** [comment]
Doesn't look too bad, maybe get rid of, or at least lower, the noise around the edges though?

**Comment by ajloveslily14** [comment]
There we go, better?

**Comment by Hanse00** [comment]
I definitely like it! Would love to hear what @yonsaber thinks before I merge this in.

Here's an image of the on version, if someone wants to see:

**Comment by GUIpsp** [comment]
Wait until the license is changed.

**Comment by ajloveslily14** [comment]
Is there licensing probs? and idk who yonsaber is so ok.

**Comment by Hanse00** [comment]
That was the plan with the license, it's not a "problem" per se, but we'd need your permission to change the license, which is planned to happen very soon.

**Comment by ajloveslily14** [comment]
My permission or GUIs?

**Comment by Hanse00** [comment]
Every person who's contributed, so if we hold off on this until it's changed, that's one less person to get permission from.

Don't worry, you don't have to take any actions.

**Comment by yonsaber** [comment]
Nice work on the texture @ajloveslily14! Far better than what we had before! 

I'm just another developer on this project :)

@Hanse00 I am just looking over #39

**Pull request merged**
