### PR TITLE
Feature crusher

### PR DESCRIPTION
**Pull request by yonsaber**
Added functionality to crusher.
Added working GUI.
Added item output and input.

Hopefully this can be added for Alpha2?

What do you think @Hanse00 

ToDo:
- ~~Crafting Recipe~~
- ~~Front side 'on' animation~~
-    Fix mistakes
-    SidedInventory

### CODE REVIEW

**Comment by Hanse00** [comment]
Crashed with the following message after the crusher had been running for a little while (generated 3 \* 2 limestone dust I believe).

```
---- Minecraft Crash Report ----
// Don't do that.

Time: 27-02-14 13:50
Description: Ticking block entity

java.lang.ArrayIndexOutOfBoundsException: 3
    at dk.philiphansen.craftech.tileentities.TileentityCrusher.getStackInSlot(TileentityCrusher.java:55)
    at dk.philiphansen.craftech.tileentities.TileentityCrusher.completeProcess(TileentityCrusher.java:259)
    at dk.philiphansen.craftech.tileentities.TileentityCrusher.updateEntity(TileentityCrusher.java:190)
    at net.minecraft.world.World.updateEntities(World.java:2148)
    at net.minecraft.world.WorldServer.updateEntities(WorldServer.java:536)
    at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:740)
    at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:651)
    at net.minecraft.server.integrated.IntegratedServer.tick(IntegratedServer.java:120)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:530)
    at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:788)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
    at dk.philiphansen.craftech.tileentities.TileentityCrusher.getStackInSlot(TileentityCrusher.java:55)
    at dk.philiphansen.craftech.tileentities.TileentityCrusher.completeProcess(TileentityCrusher.java:259)
    at dk.philiphansen.craftech.tileentities.TileentityCrusher.updateEntity(TileentityCrusher.java:190)

-- Block entity being ticked --
Details:
    Name: blockCrusher // dk.philiphansen.craftech.tileentities.TileentityCrusher
    Block type: ID #176 (tile.blockCrusher // dk.philiphansen.craftech.blocks.BlockCrusher)
    Block data value: 3 / 0x3 / 0b0011
    Block location: World: (-209,95,-61), Chunk: (at 15,5,3 in -14,-4; contains blocks -224,0,-64 to -209,255,-49), Region: (-1,-1; contains chunks -32,-32 to -1,-1, blocks -512,0,-512 to -1,255,-1)
    Actual block type: ID #176 (tile.blockCrusher // dk.philiphansen.craftech.blocks.BlockCrusher)
    Actual block data value: 3 / 0x3 / 0b0011
Stacktrace:
    at net.minecraft.world.World.updateEntities(World.java:2148)
    at net.minecraft.world.WorldServer.updateEntities(WorldServer.java:536)

-- Affected level --
Details:
    Level name: New World
    All players: 1 total; [EntityPlayerMP['Player474'/298, l='New World', x=-209,47, y=95,00, z=-63,09]]
    Chunk stats: ServerChunkCache: 762 Drop: 0
    Level seed: 1774209450
    Level generator: ID 00 - default, ver 1. Features enabled: true
    Level generator options: 
    Level spawn location: World: (-60,64,-36), Chunk: (at 4,4,12 in -4,-3; contains blocks -64,0,-48 to -49,255,-33), Region: (-1,-1; contains chunks -32,-32 to -1,-1, blocks -512,0,-512 to -1,255,-1)
    Level time: 8576 game time, 8576 day time
    Level dimension: 0
    Level storage version: 0x04ABD - Anvil
    Level weather: Rain time: 123546 (now: false), thunder time: 74630 (now: false)
    Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: true
Stacktrace:
    at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:740)
    at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:651)
    at net.minecraft.server.integrated.IntegratedServer.tick(IntegratedServer.java:120)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:530)
    at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:788)

-- System Details --
Details:
    Minecraft Version: 1.7.2
    Operating System: Windows 7 (amd64) version 6.1
    Java Version: 1.7.0_45, Oracle Corporation
    Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
    Memory: 814825776 bytes (777 MB) / 1056309248 bytes (1007 MB) up to 1056309248 bytes (1007 MB)
    JVM Flags: 3 total; -Xincgc -Xmx1024M -Xms1024M
    AABB Pool Size: 3809 (213304 bytes; 0 MB) allocated, 3625 (203000 bytes; 0 MB) used
    IntCache: cache: 0, tcache: 0, allocated: 12, tallocated: 94
    FML: MCP v9.01-pre FML v7.2.125.1031 Minecraft Forge 10.12.0.1031 4 mods loaded, 4 mods active
    mcp{8.09} [Minecraft Coder Pack] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    FML{7.2.125.1031} [Forge Mod Loader] (forgeSrc-1.7.2-10.12.0.1031.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    Forge{10.12.0.1031} [Minecraft Forge] (forgeSrc-1.7.2-10.12.0.1031.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    craftech{0.1a1} [CrafTech] (bin) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    Profiler Position: N/A (disabled)
    Vec3 Pool Size: 1677 (93912 bytes; 0 MB) allocated, 962 (53872 bytes; 0 MB) used
    Player Count: 1 / 8; [EntityPlayerMP['Player474'/298, l='New World', x=-209,47, y=95,00, z=-63,09]]
    Type: Integrated Server (map_client.txt)
    Is Modded: Definitely; Client brand changed to 'fml,forge'
```

Need to check out what's up with that.

Also I think you should do the following things before we merge in the branch:
- Only allow items that can be processed by the machine to be put in the top slot
- Change blast furnace to use dusts rather than items

**Comment by yonsaber** [comment]
For the crash, that is a simple thing to fix, its just attempting to look at a null slot (slot 3) instead of slot 1.

That is a shift clicking thing that I need to look into and I am on that currently.

I can quickly make the modifications to blast furnace for sure.

**Comment by Hanse00** [comment]
Well leave a comment here when you have all of that done, and we'll run it through another round of tests.

Happy coding :coffee:

**Comment by yonsaber** [comment]
Those should be all fixed up.

Bit more testing then we should be good!

**Comment by Hanse00** [comment]
If the output stack is full, the machine will still run, hence wasting the materials that are input.
Add a check if the output slot can actually contain the result of the process, before running it.

Another graphical issue is that it seems like the on animation is constantly running, even when it's not the applied texture to the block, this means that when the block does activate, it might be mid animation, and jump to some other state of the animated front icon, rather than starting from the beginning.

On a side note, it doesn't hurt to have multiple commit, I'd rather that you do one commit for every issue you fix, than just one "fixed these things" commit.

Once these two things are working, it looks like we're ready for :ship: time.

**Comment by yonsaber** [comment]
Right I think that should be it! 

@Hanse00 :ship:ing time?

**Comment by Hanse00** [comment]
The output stack part is fixed now, the texture issue still persists though, let me try to explain it, as I think you misunderstood me.

The on texture seems to continuously cycle between the textures, which makes sense when it's on. But the point is if the on texture is in state 4, for example, when the block changes from off to on, it skips to state 4 in the texture, rather than starting over.

**Comment by yonsaber** [comment]
Hmm, I am having a look at this but I have no idea what is causing it, I have a small idea how to fix it though. Skype ?

**Comment by Hanse00** [comment]
I imagine it has something to do with the fact that it works somewhat like an animated gif, from the moment you register the texture, it just continues cycling, that'd also explain why, if you place down multiple crushers, their animation is perfectly in sync.

Look at figuring something out to pause the animation when it's not the texture being shown, or maybe just rebinding the texture when the icon changes? I'm not really sure, you'll have to look at it.

I'll be largely unavailable until tomorrow night.

**Comment by yonsaber** [comment]
I have a feeling it might be a core Minecraft thing. I'll keep looking into it.

Should we merge and deal with that issue for another release?

**Comment by Hanse00** [comment]
I think we should off on it for now, try to get that texture working well, and we'll fix up the blast furnace in the mean time.

**Comment by Hanse00** [comment]
Alright, I think I've worked out what we need to do to get the animation working the way I want it to.

It's a rather large programmatic change though, so I'm merging this branch in at the time, and working out the animation is a separate branch to be merged in later.

It's :ship: time for the crusher!

**Pull request merged**
