### PR TITLE
Feature custom creative tab

### PR DESCRIPTION
**Pull request by yonsaber**
I messed up a little, closed the pull instead or merging. I am not smart at times

### CODE REVIEW

**Comment by yonsaber** [comment]
That's better

**Comment by Hanse00** [comment]
Did you test the code before merging it?

Do as you wish, but by merging a branch you're indicating that it's ready for shipping, that shouldn't be taken lightly. Or we'll end up with bugs all over the place.

**Comment by yonsaber** [comment]
Sadly not at my dev machine but from previous tests, this will work

**Comment by Hanse00** [comment]
Well it won't hurt to wait for a few hours, and if it prevents bugs, I think it's worth it.

Otherwise I could just as well be merging it in myself, that's why we have a process of letting the other person check out the code first.

For the future, please do tests before merging.

**Comment by yonsaber** [comment]
The other code I have tested. I actually wrote this code in an earlier version then removed it before committing. This is exactly the same as the code I had added.
But in future I will test pre-merge.

**Comment by Hanse00** [comment]
I remember you did, I'm not saying you didn't test before, just making a remark in general, that we should remember to test code :)

**Pull request merged**
