### PR TITLE
Machine Recipes

### PR DESCRIPTION
**Pull request by Hanse00**
This implements a special crafting table (the "Tech Table"), which is used for crafting the CrafTech machines.

The table takes the standard crafting recipe, and a recipe item, which is generated throughout the world in dungeons, mine shafts, villages, and pyramids.

This is the first, very basic, implementation of #33.

### CODE REVIEW

**Comment by yonsaber** [comment]
WOW! This is really good, hats off to you good sir!

The only other thing I can think of to add to this is maybe ghost items when you put the recipe in / a tool tip that says what it requires

**Comment by Hanse00** [comment]
That's actually a good idea, didn't think of that one.

I'm thinking we should leave it for 0.2 maybe though, and get this out the way it is, just clean up the code first.

What do you think?

**Comment by yonsaber** [comment]
For 0.2 yes.

Otherwise a code clean up will be needed. Especially with `TechTableRecipes.java`. I realise it took forever but it's not easy to understand!

**Comment by yonsaber** [comment]
I'm going to merge this as I know you will add comments and stick it in the other branch!

Nice work @Hanse00!

**Pull request merged**
